language: node_js
node_js:
  - '5'
install:
  - npm install
script:
  - ./bin/deploy-ghpages.sh
env:
  global:
    secure: Fk186bbxQmuQFaWDwb0FM0NIAQ5itsRkNZHS6D+ihckAs0Mxuwv4ZABLUrl6qky9IwXBc0rt9rEnrNS7uJinoQu/gwtfF7tbxKLw8XkwJSi+zJOOH+flLxmCPMOBZUaShI62wwJTchDYETPknVTO6w7CVl20ODmpz4fxgSmgsU4=
