language: node_js
node_js:
  - '5'
install:
  - npm install
script:
  - ./bin/deploy-ghpages.sh
env:
  global:
    secure: Xop8C8+EI8iNHco3EFMbEkYmyddawyNUeMFMDGW1DQzVxBUCzN1IDqgYJ15JlpE+oMPN9ECv4s9P4Ytd+HitipLeXbsJfsJC1gsuxTSZrvOZ1effGtpI5WOOwnMi+1nVifYU7JAwmy7D/oUpWDRknCIaFze9UpvH2Uzf0f2C9Zeo7jd802qUbL8mOdt9i86wRyhQS0purN4dgm4Djn+FZkrE90fzuD/tlAGJ1//40F/xYPknVnh7zGGwv4fc27GNGyoVONha6ofcQHJbqdiTA6INHx6wwpOY+C7WYl6tu+ObA+T6JStayRIKfG+uE9RJkj0hyhm4NFT2VNQbh/cIub8ZSSzD5bPRZzjmcwznnWGElv0eypGNtC/AfpDBnmnUQJDWjGPbqulXycMKbL6wGHqY4eiGxhFoHiHauWd7Vbm5ox5l9v6Q34Jjv8BrY9ULf6bdycq1jFchnuA2SheejEZ4y0knNb46H0BgLlcd/ft0HP/ZonZ2buk+69qb27br5ihCkoq2h31R2syhm1/20GU8PF4HQXgpolksFwgkKsVjmEepXcew6u/AejOyfizKXn0F7InF74X+H+aln/8ejBV22AmcihKf59vxB7uqrmLolF9UXE7j0vewb2x58+rL8Or/P3rZ9AYLCzlbXu5ufrq9TPZC5t9cCWIm+b0C58Y=
